from typing import Dict, Any, List, Optional
from datetime import datetime
import json


class ReportFormat:
    """Supported report formats."""
    MARKDOWN = "markdown"
    JSON = "json"
    HTML = "html"
    PDF = "pdf"


class ReportGenerator:
    """Generate reports in multiple formats."""
    
    def __init__(self):
        self.formats = {
            ReportFormat.MARKDOWN: self._generate_markdown,
            ReportFormat.JSON: self._generate_json,
            ReportFormat.HTML: self._generate_html,
        }
    
    def generate_report(
        self,
        method_id: str,
        trust_score: Any,
        reasoning: Any,
        constraint_report: Any,
        robustness_report: Any,
        risk_report: Any,
        format: str = ReportFormat.MARKDOWN
    ) -> str:
        """Generate report in specified format."""
        if format not in self.formats:
            raise ValueError(f"Unsupported format: {format}")
        
        return self.formats[format](
            method_id, trust_score, reasoning,
            constraint_report, robustness_report, risk_report
        )
    
    def _generate_markdown(
        self,
        method_id: str,
        trust_score: Any,
        reasoning: Any,
        constraint_report: Any,
        robustness_report: Any,
        risk_report: Any
    ) -> str:
        """Generate markdown report."""
        report = f"""# EluSight Chromatographic Method Assessment Report

**Method ID:** {method_id}
**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Executive Summary

{reasoning.conclusion if hasattr(reasoning, 'conclusion') else 'No reasoning available'}

**Overall Trust Score:** {trust_score.overall_score:.1f}/100
**Recommendation:** {trust_score.recommendation}

## Detailed Assessment

### Constraint Analysis

| Constraint | Status | Value | Margin |
|------------|--------|-------|--------|
"""
        
        if hasattr(constraint_report, 'constraints'):
            for c in constraint_report.constraints:
                status = "✓" if c.passed else "✗"
                report += f"| {c.name} | {status} | {c.actual_value:.2f} | {c.margin_percentage:.1f}% |\n"
        
        report += f"""
### Robustness Assessment

- **Robustness Score:** {robustness_report.overall_robustness_score*100:.1f}%
- **Success Probability:** {robustness_report.method_robustness.pass_probability*100:.1f}%
- **Critical Parameters:** {', '.join(robustness_report.method_robustness.critical_parameters)}

### Risk Assessment

| Risk Factor | Probability |
|-------------|-------------|
| Co-elution | {risk_report.risk_metrics.coelution_probability*100:.1f}% |
| SST Failure | {risk_report.risk_metrics.sst_failure_probability*100:.1f}% |
| Overall Risk | {risk_report.risk_metrics.overall_risk_score*100:.1f}% |

### Scientific Reasoning

"""
        
        if hasattr(reasoning, 'reasoning_steps'):
            for i, step in enumerate(reasoning.reasoning_steps[:3], 1):
                report += f"#### Step {i}: {step.claim}\n\n"
                for evidence in step.evidence[:2]:
                    report += f"- {evidence}\n"
                report += f"\n*Confidence: {step.confidence*100:.1f}%*\n\n"
        
        report += f"""
### Trust Score Breakdown

- Constraint Satisfaction: {trust_score.constraint_score:.1f}/100
- Robustness: {trust_score.robustness_score:.1f}/100
- Confidence: {trust_score.confidence_score:.1f}/100
- Risk Management: {trust_score.risk_score:.1f}/100

### Final Recommendation

{reasoning.recommendation if hasattr(reasoning, 'recommendation') else 'No recommendation available'}

---
*Report generated by EluSight - Chromatographic Decision Intelligence Framework*
"""
        
        return report
    
    def _generate_json(
        self,
        method_id: str,
        trust_score: Any,
        reasoning: Any,
        constraint_report: Any,
        robustness_report: Any,
        risk_report: Any
    ) -> str:
        """Generate JSON report."""
        report = {
            'method_id': method_id,
            'timestamp': datetime.now().isoformat(),
            'trust_score': {
                'overall': trust_score.overall_score,
                'constraints': trust_score.constraint_score,
                'robustness': trust_score.robustness_score,
                'recommendation': trust_score.recommendation
            },
            'constraints': {
                'overall_pass': constraint_report.overall_pass,
                'satisfaction_rate': constraint_report.constraint_satisfaction_rate
            },
            'robustness': {
                'score': robustness_report.overall_robustness_score,
                'pass_probability': robustness_report.method_robustness.pass_probability
            },
            'risk': {
                'overall': risk_report.risk_metrics.overall_risk_score,
                'acceptability': risk_report.risk_acceptability
            },
            'reasoning': {
                'conclusion': reasoning.conclusion if hasattr(reasoning, 'conclusion') else '',
                'recommendation': reasoning.recommendation if hasattr(reasoning, 'recommendation') else ''
            }
        }
        
        return json.dumps(report, indent=2)
    
    def _generate_html(
        self,
        method_id: str,
        trust_score: Any,
        reasoning: Any,
        constraint_report: Any,
        robustness_report: Any,
        risk_report: Any
    ) -> str:
        """Generate HTML report."""
        markdown = self._generate_markdown(
            method_id, trust_score, reasoning,
            constraint_report, robustness_report, risk_report
        )
        
        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>EluSight Report - {method_id}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
        h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
        th {{ background-color: #3498db; color: white; }}
        .trust-score {{ font-size: 48px; font-weight: bold; color: #27ae60; }}
        .recommendation {{ padding: 10px; border-radius: 5px; margin: 20px 0; }}
        .strongly-recommend {{ background-color: #d4edda; color: #155724; }}
        .recommend {{ background-color: #d1ecf1; color: #0c5460; }}
        .consider {{ background-color: #fff3cd; color: #856404; }}
        .avoid {{ background-color: #f8d7da; color: #721c24; }}
    </style>
</head>
<body>
    <div style="max-width: 1200px; margin: 0 auto;">
        <pre style="white-space: pre-wrap; font-family: inherit;">{markdown}</pre>
    </div>
</body>
</html>"""
        return html
EOF
